first version
gridsuite/config-notification-server pull request #1
Opened 2020-11-30 10:25 UTC by AbdelHedhili

Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>

2020-12-28 09:51 UTC, AbdelHedhili commented on src/main/java/org/gridsuite/config/notification/server/NotificationWebSocketHandler.java
> +        HttpHeaders headers = webSocketSession.getHandshakeInfo().getHeaders();
i do filter, i only retrieve the userId : 
`String filterUserId = headers.getFirst(HEADER_USER_ID);`

2020-12-28 10:21 UTC, AbdelHedhili commented on src/test/java/org/gridsuite/config/notification/server/NotificationWebSocketIT.java
> +    public void echo() {
done

2020-12-29 09:55 UTC, SlimaneAmar approved these changes

2021-01-04 07:58 UTC, geofjamg requested changes

2021-01-04 07:58 UTC, geofjamg commented on README.md
> +# config-notification-server
Could you add all badges?

2021-01-04 13:20 UTC, merged